collection_interval_hours: 24  # Интервал сбора данных в часах
collection_interval_minutes: 1440  # Интервал сбора постов в минутах (24 часа)
fastapi_base_url: "http://127.0.0.1:8002"

backup_paths:
  posts: "backups/backup_posts.csv"
  historical: "backups/backup_historical.csv"

historical_days: 90  # Сколько дней истории загружать

reddit:
  client_id: "XjhMKpfNTmmZb04iyxjPvw"
  client_secret: "JfwSgsblu6nNJ9QQWtohggKCrhtYWw"
  username: "Wooden-Ask-4958"
  password: "Miem2025."
  user_agent: "CryptoDataCollector by /u/Wooden-Ask-4958"
